###############################
# Stage 1 - Build
###############################

FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci   #clean install 

COPY . .

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL


# RUN ls -la

# RUN cat .env

RUN npx prisma generate

RUN npm run build

###############################
# Stage 2 - Production
###############################

FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY package*.json ./

RUN npm ci --omit=dev \
    && npm cache clean --force

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma

RUN addgroup -S appgroup \
 && adduser -S appuser -G appgroup

RUN chown -R appuser:appgroup /app

USER appuser

EXPOSE 5000

CMD ["npm","start"]